# -*- encoding: utf-8 -*-

=begin
#Vectorizer.AI API

#OpenAPI 3.0 specification for the Vectorizer.AI image vectorization API. Authenticate with HTTP Basic auth, using your API Id as the username and your API Secret as the password.

The version of the OpenAPI document: 1.0.0
Contact: support@vectorizer.ai
Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "vectorizer_ai/version"

Gem::Specification.new do |s|
  s.name        = "vectorizer_ai"
  s.version     = VectorizerAI::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Vectorizer.AI"]
  s.email       = ["support@vectorizer.ai"]
  s.homepage    = "https://vectorizer.ai/api/documentation"
  s.summary     = "Vectorizer.AI API SDK"
  s.description = "Official Ruby SDK for the Vectorizer.AI image vectorization API."
  s.license     = "Apache-2.0"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {
    "source_code_uri" => "https://github.com/clv/vectorizer-ai-ruby",
    "documentation_uri" => "https://vectorizer.ai/api/documentation",
    "changelog_uri" => "https://github.com/clv/vectorizer-ai-ruby/releases",
    "rubygems_mfa_required" => "true"
  }

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = [
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "vectorizer_ai.gemspec"
  ] + Dir.glob("docs/**/*.md") + Dir.glob("lib/**/*.rb")
  s.test_files    = Dir.glob("spec/**/*.rb")
  s.executables   = []
  s.require_paths = ["lib"]
end
