=begin
#Vectorizer.AI API

#OpenAPI 3.0 specification for the Vectorizer.AI image vectorization API. Authenticate with HTTP Basic auth, using your API Id as the username and your API Secret as the password.

The version of the OpenAPI document: 1.0.0
Contact: support@vectorizer.ai
Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

module VectorizerAI
  VERSION = '1.0.2'
end
