=begin
#Vectorizer.AI API

#OpenAPI 3.0 specification for the Vectorizer.AI image vectorization API. Authenticate with HTTP Basic auth, using your API Id as the username and your API Secret as the password.

The version of the OpenAPI document: 1.0.0
Contact: support@vectorizer.ai
Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

# Common files
require 'vectorizer_ai/api_client'
require 'vectorizer_ai/api_error'
require 'vectorizer_ai/version'
require 'vectorizer_ai/configuration'

# Models
require 'vectorizer_ai/models/account_status_response'
require 'vectorizer_ai/models/delete_image_response'
require 'vectorizer_ai/models/error_response'
require 'vectorizer_ai/models/error_response_error'

# APIs
require 'vectorizer_ai/api/account_api'
require 'vectorizer_ai/api/vectorization_api'

module VectorizerAI
  class << self
    # Customize default settings for the SDK using block.
    #   VectorizerAI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
