=begin
#Vectorizer.AI API

#OpenAPI 3.0 specification for the Vectorizer.AI image vectorization API. Authenticate with HTTP Basic auth, using your API Id as the username and your API Secret as the password.

The version of the OpenAPI document: 1.0.0
Contact: support@vectorizer.ai
Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'cgi'

module VectorizerAI
  class AccountApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get account status
    # Fetch the subscription state and remaining API credits for the authenticated account.
    # @param [Hash] opts the parameters
    # @return [AccountStatusResponse]
    def get_account_status(opts = {})
      data, _status_code, _headers = get_account_status_with_http_info(opts)
      data
    end

    # Get account status
    # Fetch the subscription state and remaining API credits for the authenticated account.
    # @param [Hash] opts the parameters
    # @return [Array<(AccountStatusResponse, Integer, Hash)>] AccountStatusResponse data, response status code and response headers
    def get_account_status_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AccountApi.get_account_status ...'
      end
      # unbox the parameters from the hash
      # resource path
      local_var_path = '/account'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AccountStatusResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['basicAuth']

      new_options = opts.merge(
        :operation => :"AccountApi.get_account_status",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AccountApi#get_account_status\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
