=begin
#Vectorizer.AI API

#OpenAPI 3.0 specification for the Vectorizer.AI image vectorization API. Authenticate with HTTP Basic auth, using your API Id as the username and your API Secret as the password.

The version of the OpenAPI document: 1.0.0
Contact: support@vectorizer.ai
Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'cgi'

module VectorizerAI
  class VectorizationApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Delete a retained image
    # Delete a retained image and result before its retention period expires.
    # @param [Hash] opts the parameters
    # @option opts [String] :image_token Image Token to delete before its retention period expires. (required)
    # @return [DeleteImageResponse]
    def post_delete(opts = {})
      data, _status_code, _headers = post_delete_with_http_info(opts)
      data
    end

    # Delete a retained image
    # Delete a retained image and result before its retention period expires.
    # @param [Hash] opts the parameters
    # @option opts [String] :image_token Image Token to delete before its retention period expires. (required)
    # @return [Array<(DeleteImageResponse, Integer, Hash)>] DeleteImageResponse data, response status code and response headers
    def post_delete_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: VectorizationApi.post_delete ...'
      end
      # unbox the parameters from the hash
      image_token = opts[:'image_token']
      # verify the required parameter 'image_token' is set
      if @api_client.config.client_side_validation && image_token.nil?
        fail ArgumentError, "Missing the required parameter 'image_token' when calling VectorizationApi.post_delete"
      end
      # resource path
      local_var_path = '/delete'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}
      form_params['image.token'] = image_token

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'DeleteImageResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['basicAuth']

      new_options = opts.merge(
        :operation => :"VectorizationApi.post_delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: VectorizationApi#post_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Download a retained result
    # Download a production result from a retained Image Token, optionally changing output.file_format and other output options. Include receipt when downloading additional formats after upgrading a preview result.
    # @param [Hash] opts the parameters
    # @option opts [String] :image_token Image Token returned from a vectorize request with policy.retention_days &gt; 0. (required)
    # @option opts [String] :receipt Receipt returned in the X-Receipt response header when upgrading a preview result to production. Include it when downloading additional formats from that upgraded preview.
    # @option opts [String] :output_file_format Output file format to generate. (default to 'svg')
    # @option opts [String] :output_shape_stacking Whether shapes are cut out of each other or stacked atop each other. (default to 'cutouts')
    # @option opts [String] :output_group_by Grouping of shapes in output. (default to 'none')
    # @option opts [String] :output_draw_style How shapes are rendered. (default to 'fill_shapes')
    # @option opts [Float] :output_strokes_stroke_width Width of stroke for shape outlines (when enabled). (default to 1)
    # @option opts [Boolean] :output_strokes_non_scaling_stroke Use non-scaling strokes when drawing shape outlines. (default to true)
    # @option opts [Boolean] :output_strokes_use_override_color Override shape color with a specific color. (default to false)
    # @option opts [String] :output_strokes_override_color Color value to override shape stroke color if enabled. Must be in &#39;#RRGGBB&#39; or &#39;rgba(r,g,b,a)&#39; format. (default to '#000000')
    # @option opts [Boolean] :output_gap_filler_enabled Enable filling small visual gaps caused by vector rendering artifacts. (default to true)
    # @option opts [Boolean] :output_gap_filler_non_scaling_stroke Use non-scaling strokes for gap filling. (default to true)
    # @option opts [Boolean] :output_gap_filler_clip Clip gap filler strokes to shape bounds when stacking shapes. (default to false)
    # @option opts [Float] :output_gap_filler_stroke_width Width of the gap filler strokes (in output units). (default to 2)
    # @option opts [Boolean] :output_parameterized_shapes_flatten Whether to flatten detected circles, rectangles, and stars to curves. (default to false)
    # @option opts [Float] :output_curves_line_fit_tolerance Maximum allowed error when approximating curves with line segments. (default to 0.1)
    # @option opts [Boolean] :output_curves_allowed_quadratic_bezier Allow quadratic Bézier curves in the output. (default to true)
    # @option opts [Boolean] :output_curves_allowed_cubic_bezier Allow cubic Bézier curves in the output. (default to true)
    # @option opts [Boolean] :output_curves_allowed_circular_arc Allow circular arcs in the output. (default to true)
    # @option opts [Boolean] :output_curves_allowed_elliptical_arc Allow elliptical arcs in the output. (default to true)
    # @option opts [String] :output_svg_version SVG version to declare in the SVG output. (default to 'svg_1_1')
    # @option opts [Boolean] :output_svg_fixed_size Whether to fix the SVG dimensions in the output file. (default to false)
    # @option opts [Boolean] :output_svg_adobe_compatibility_mode Enable Illustrator compatibility by disabling unsupported SVG features. (default to false)
    # @option opts [String] :output_pdf_version PDF version to generate for PDF output. (default to 'PDF_1_4')
    # @option opts [String] :output_pdf_compression_mode Compression method to apply to PDF output streams. (default to 'Deflate')
    # @option opts [String] :output_eps_version EPS format version for EPS output. (default to 'PS_3_0_EPSF_3_0')
    # @option opts [String] :output_dxf_compatibility_level Level of primitive support for DXF output. (default to 'lines_and_arcs')
    # @option opts [String] :output_bitmap_anti_aliasing_mode Anti-aliasing mode for bitmap (PNG) output. (default to 'anti_aliased')
    # @option opts [Float] :output_size_scale Overall uniform scaling factor for the output image.
    # @option opts [Float] :output_size_width Output width, in the selected unit (see output.size.unit).
    # @option opts [Float] :output_size_height Output height, in the selected unit (see output.size.unit).
    # @option opts [String] :output_size_unit Measurement unit for output dimensions. (default to 'none')
    # @option opts [String] :output_size_aspect_ratio How to preserve or stretch aspect ratio. (default to 'preserve_inset')
    # @option opts [Float] :output_size_align_x Horizontal alignment (0.0 &#x3D; left, 0.5 &#x3D; center, 1.0 &#x3D; right) when aspect ratio is preserved. (default to 0.5)
    # @option opts [Float] :output_size_align_y Vertical alignment (0.0 &#x3D; top, 0.5 &#x3D; center, 1.0 &#x3D; bottom) when aspect ratio is preserved. (default to 0.5)
    # @option opts [Float] :output_size_input_dpi Override the detected DPI of the input image for size computations.
    # @option opts [Float] :output_size_output_dpi DPI setting for the output image.
    # @return [File]
    def post_download(opts = {})
      data, _status_code, _headers = post_download_with_http_info(opts)
      data
    end

    # Download a retained result
    # Download a production result from a retained Image Token, optionally changing output.file_format and other output options. Include receipt when downloading additional formats after upgrading a preview result.
    # @param [Hash] opts the parameters
    # @option opts [String] :image_token Image Token returned from a vectorize request with policy.retention_days &gt; 0. (required)
    # @option opts [String] :receipt Receipt returned in the X-Receipt response header when upgrading a preview result to production. Include it when downloading additional formats from that upgraded preview.
    # @option opts [String] :output_file_format Output file format to generate. (default to 'svg')
    # @option opts [String] :output_shape_stacking Whether shapes are cut out of each other or stacked atop each other. (default to 'cutouts')
    # @option opts [String] :output_group_by Grouping of shapes in output. (default to 'none')
    # @option opts [String] :output_draw_style How shapes are rendered. (default to 'fill_shapes')
    # @option opts [Float] :output_strokes_stroke_width Width of stroke for shape outlines (when enabled). (default to 1)
    # @option opts [Boolean] :output_strokes_non_scaling_stroke Use non-scaling strokes when drawing shape outlines. (default to true)
    # @option opts [Boolean] :output_strokes_use_override_color Override shape color with a specific color. (default to false)
    # @option opts [String] :output_strokes_override_color Color value to override shape stroke color if enabled. Must be in &#39;#RRGGBB&#39; or &#39;rgba(r,g,b,a)&#39; format. (default to '#000000')
    # @option opts [Boolean] :output_gap_filler_enabled Enable filling small visual gaps caused by vector rendering artifacts. (default to true)
    # @option opts [Boolean] :output_gap_filler_non_scaling_stroke Use non-scaling strokes for gap filling. (default to true)
    # @option opts [Boolean] :output_gap_filler_clip Clip gap filler strokes to shape bounds when stacking shapes. (default to false)
    # @option opts [Float] :output_gap_filler_stroke_width Width of the gap filler strokes (in output units). (default to 2)
    # @option opts [Boolean] :output_parameterized_shapes_flatten Whether to flatten detected circles, rectangles, and stars to curves. (default to false)
    # @option opts [Float] :output_curves_line_fit_tolerance Maximum allowed error when approximating curves with line segments. (default to 0.1)
    # @option opts [Boolean] :output_curves_allowed_quadratic_bezier Allow quadratic Bézier curves in the output. (default to true)
    # @option opts [Boolean] :output_curves_allowed_cubic_bezier Allow cubic Bézier curves in the output. (default to true)
    # @option opts [Boolean] :output_curves_allowed_circular_arc Allow circular arcs in the output. (default to true)
    # @option opts [Boolean] :output_curves_allowed_elliptical_arc Allow elliptical arcs in the output. (default to true)
    # @option opts [String] :output_svg_version SVG version to declare in the SVG output. (default to 'svg_1_1')
    # @option opts [Boolean] :output_svg_fixed_size Whether to fix the SVG dimensions in the output file. (default to false)
    # @option opts [Boolean] :output_svg_adobe_compatibility_mode Enable Illustrator compatibility by disabling unsupported SVG features. (default to false)
    # @option opts [String] :output_pdf_version PDF version to generate for PDF output. (default to 'PDF_1_4')
    # @option opts [String] :output_pdf_compression_mode Compression method to apply to PDF output streams. (default to 'Deflate')
    # @option opts [String] :output_eps_version EPS format version for EPS output. (default to 'PS_3_0_EPSF_3_0')
    # @option opts [String] :output_dxf_compatibility_level Level of primitive support for DXF output. (default to 'lines_and_arcs')
    # @option opts [String] :output_bitmap_anti_aliasing_mode Anti-aliasing mode for bitmap (PNG) output. (default to 'anti_aliased')
    # @option opts [Float] :output_size_scale Overall uniform scaling factor for the output image.
    # @option opts [Float] :output_size_width Output width, in the selected unit (see output.size.unit).
    # @option opts [Float] :output_size_height Output height, in the selected unit (see output.size.unit).
    # @option opts [String] :output_size_unit Measurement unit for output dimensions. (default to 'none')
    # @option opts [String] :output_size_aspect_ratio How to preserve or stretch aspect ratio. (default to 'preserve_inset')
    # @option opts [Float] :output_size_align_x Horizontal alignment (0.0 &#x3D; left, 0.5 &#x3D; center, 1.0 &#x3D; right) when aspect ratio is preserved. (default to 0.5)
    # @option opts [Float] :output_size_align_y Vertical alignment (0.0 &#x3D; top, 0.5 &#x3D; center, 1.0 &#x3D; bottom) when aspect ratio is preserved. (default to 0.5)
    # @option opts [Float] :output_size_input_dpi Override the detected DPI of the input image for size computations.
    # @option opts [Float] :output_size_output_dpi DPI setting for the output image.
    # @return [Array<(File, Integer, Hash)>] File data, response status code and response headers
    def post_download_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: VectorizationApi.post_download ...'
      end
      # unbox the parameters from the hash
      image_token = opts[:'image_token']
      # verify the required parameter 'image_token' is set
      if @api_client.config.client_side_validation && image_token.nil?
        fail ArgumentError, "Missing the required parameter 'image_token' when calling VectorizationApi.post_download"
      end
      allowable_values = ["svg", "eps", "pdf", "dxf", "png"]
      if @api_client.config.client_side_validation && opts[:'output_file_format'] && !allowable_values.include?(opts[:'output_file_format'])
        fail ArgumentError, "invalid value for \"output_file_format\", must be one of #{allowable_values}"
      end
      allowable_values = ["cutouts", "stacked"]
      if @api_client.config.client_side_validation && opts[:'output_shape_stacking'] && !allowable_values.include?(opts[:'output_shape_stacking'])
        fail ArgumentError, "invalid value for \"output_shape_stacking\", must be one of #{allowable_values}"
      end
      allowable_values = ["none", "color", "parent", "layer"]
      if @api_client.config.client_side_validation && opts[:'output_group_by'] && !allowable_values.include?(opts[:'output_group_by'])
        fail ArgumentError, "invalid value for \"output_group_by\", must be one of #{allowable_values}"
      end
      allowable_values = ["fill_shapes", "stroke_shapes", "stroke_edges"]
      if @api_client.config.client_side_validation && opts[:'output_draw_style'] && !allowable_values.include?(opts[:'output_draw_style'])
        fail ArgumentError, "invalid value for \"output_draw_style\", must be one of #{allowable_values}"
      end
      if @api_client.config.client_side_validation && !opts[:'output_strokes_stroke_width'].nil? && opts[:'output_strokes_stroke_width'] > 5
        fail ArgumentError, 'invalid value for "opts[:"output_strokes_stroke_width"]" when calling VectorizationApi.post_download, must be smaller than or equal to 5.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_strokes_stroke_width'].nil? && opts[:'output_strokes_stroke_width'] < 0
        fail ArgumentError, 'invalid value for "opts[:"output_strokes_stroke_width"]" when calling VectorizationApi.post_download, must be greater than or equal to 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_gap_filler_stroke_width'].nil? && opts[:'output_gap_filler_stroke_width'] > 5
        fail ArgumentError, 'invalid value for "opts[:"output_gap_filler_stroke_width"]" when calling VectorizationApi.post_download, must be smaller than or equal to 5.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_gap_filler_stroke_width'].nil? && opts[:'output_gap_filler_stroke_width'] < 0
        fail ArgumentError, 'invalid value for "opts[:"output_gap_filler_stroke_width"]" when calling VectorizationApi.post_download, must be greater than or equal to 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_curves_line_fit_tolerance'].nil? && opts[:'output_curves_line_fit_tolerance'] > 1
        fail ArgumentError, 'invalid value for "opts[:"output_curves_line_fit_tolerance"]" when calling VectorizationApi.post_download, must be smaller than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_curves_line_fit_tolerance'].nil? && opts[:'output_curves_line_fit_tolerance'] < 0.001
        fail ArgumentError, 'invalid value for "opts[:"output_curves_line_fit_tolerance"]" when calling VectorizationApi.post_download, must be greater than or equal to 0.001.'
      end

      allowable_values = ["svg_1_0", "svg_1_1", "svg_tiny_1_2"]
      if @api_client.config.client_side_validation && opts[:'output_svg_version'] && !allowable_values.include?(opts[:'output_svg_version'])
        fail ArgumentError, "invalid value for \"output_svg_version\", must be one of #{allowable_values}"
      end
      allowable_values = ["PDF_1_4"]
      if @api_client.config.client_side_validation && opts[:'output_pdf_version'] && !allowable_values.include?(opts[:'output_pdf_version'])
        fail ArgumentError, "invalid value for \"output_pdf_version\", must be one of #{allowable_values}"
      end
      allowable_values = ["None", "Deflate"]
      if @api_client.config.client_side_validation && opts[:'output_pdf_compression_mode'] && !allowable_values.include?(opts[:'output_pdf_compression_mode'])
        fail ArgumentError, "invalid value for \"output_pdf_compression_mode\", must be one of #{allowable_values}"
      end
      allowable_values = ["PS_3_0_EPSF_3_0"]
      if @api_client.config.client_side_validation && opts[:'output_eps_version'] && !allowable_values.include?(opts[:'output_eps_version'])
        fail ArgumentError, "invalid value for \"output_eps_version\", must be one of #{allowable_values}"
      end
      allowable_values = ["lines_only", "lines_and_arcs", "lines_arcs_and_splines"]
      if @api_client.config.client_side_validation && opts[:'output_dxf_compatibility_level'] && !allowable_values.include?(opts[:'output_dxf_compatibility_level'])
        fail ArgumentError, "invalid value for \"output_dxf_compatibility_level\", must be one of #{allowable_values}"
      end
      allowable_values = ["anti_aliased", "aliased"]
      if @api_client.config.client_side_validation && opts[:'output_bitmap_anti_aliasing_mode'] && !allowable_values.include?(opts[:'output_bitmap_anti_aliasing_mode'])
        fail ArgumentError, "invalid value for \"output_bitmap_anti_aliasing_mode\", must be one of #{allowable_values}"
      end
      if @api_client.config.client_side_validation && !opts[:'output_size_scale'].nil? && opts[:'output_size_scale'] > 1000
        fail ArgumentError, 'invalid value for "opts[:"output_size_scale"]" when calling VectorizationApi.post_download, must be smaller than or equal to 1000.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_scale'].nil? && opts[:'output_size_scale'] < 0
        fail ArgumentError, 'invalid value for "opts[:"output_size_scale"]" when calling VectorizationApi.post_download, must be greater than or equal to 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_width'].nil? && opts[:'output_size_width'] > 1000000000000
        fail ArgumentError, 'invalid value for "opts[:"output_size_width"]" when calling VectorizationApi.post_download, must be smaller than or equal to 1000000000000.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_width'].nil? && opts[:'output_size_width'] < 0
        fail ArgumentError, 'invalid value for "opts[:"output_size_width"]" when calling VectorizationApi.post_download, must be greater than or equal to 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_height'].nil? && opts[:'output_size_height'] > 1000000000000
        fail ArgumentError, 'invalid value for "opts[:"output_size_height"]" when calling VectorizationApi.post_download, must be smaller than or equal to 1000000000000.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_height'].nil? && opts[:'output_size_height'] < 0
        fail ArgumentError, 'invalid value for "opts[:"output_size_height"]" when calling VectorizationApi.post_download, must be greater than or equal to 0.'
      end

      allowable_values = ["none", "px", "pt", "in", "cm", "mm"]
      if @api_client.config.client_side_validation && opts[:'output_size_unit'] && !allowable_values.include?(opts[:'output_size_unit'])
        fail ArgumentError, "invalid value for \"output_size_unit\", must be one of #{allowable_values}"
      end
      allowable_values = ["preserve_inset", "preserve_overflow", "stretch"]
      if @api_client.config.client_side_validation && opts[:'output_size_aspect_ratio'] && !allowable_values.include?(opts[:'output_size_aspect_ratio'])
        fail ArgumentError, "invalid value for \"output_size_aspect_ratio\", must be one of #{allowable_values}"
      end
      if @api_client.config.client_side_validation && !opts[:'output_size_align_x'].nil? && opts[:'output_size_align_x'] > 1
        fail ArgumentError, 'invalid value for "opts[:"output_size_align_x"]" when calling VectorizationApi.post_download, must be smaller than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_align_x'].nil? && opts[:'output_size_align_x'] < 0
        fail ArgumentError, 'invalid value for "opts[:"output_size_align_x"]" when calling VectorizationApi.post_download, must be greater than or equal to 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_align_y'].nil? && opts[:'output_size_align_y'] > 1
        fail ArgumentError, 'invalid value for "opts[:"output_size_align_y"]" when calling VectorizationApi.post_download, must be smaller than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_align_y'].nil? && opts[:'output_size_align_y'] < 0
        fail ArgumentError, 'invalid value for "opts[:"output_size_align_y"]" when calling VectorizationApi.post_download, must be greater than or equal to 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_input_dpi'].nil? && opts[:'output_size_input_dpi'] > 1000000
        fail ArgumentError, 'invalid value for "opts[:"output_size_input_dpi"]" when calling VectorizationApi.post_download, must be smaller than or equal to 1000000.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_input_dpi'].nil? && opts[:'output_size_input_dpi'] < 1
        fail ArgumentError, 'invalid value for "opts[:"output_size_input_dpi"]" when calling VectorizationApi.post_download, must be greater than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_output_dpi'].nil? && opts[:'output_size_output_dpi'] > 1000000
        fail ArgumentError, 'invalid value for "opts[:"output_size_output_dpi"]" when calling VectorizationApi.post_download, must be smaller than or equal to 1000000.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_output_dpi'].nil? && opts[:'output_size_output_dpi'] < 1
        fail ArgumentError, 'invalid value for "opts[:"output_size_output_dpi"]" when calling VectorizationApi.post_download, must be greater than or equal to 1.'
      end

      # resource path
      local_var_path = '/download'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['image/svg+xml', 'application/postscript', 'application/pdf', 'application/dxf', 'image/png', 'application/json'])
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}
      form_params['image.token'] = image_token
      form_params['receipt'] = opts[:'receipt'] if !opts[:'receipt'].nil?
      form_params['output.file_format'] = opts[:'output_file_format'] if !opts[:'output_file_format'].nil?
      form_params['output.shape_stacking'] = opts[:'output_shape_stacking'] if !opts[:'output_shape_stacking'].nil?
      form_params['output.group_by'] = opts[:'output_group_by'] if !opts[:'output_group_by'].nil?
      form_params['output.draw_style'] = opts[:'output_draw_style'] if !opts[:'output_draw_style'].nil?
      form_params['output.strokes.stroke_width'] = opts[:'output_strokes_stroke_width'] if !opts[:'output_strokes_stroke_width'].nil?
      form_params['output.strokes.non_scaling_stroke'] = opts[:'output_strokes_non_scaling_stroke'] if !opts[:'output_strokes_non_scaling_stroke'].nil?
      form_params['output.strokes.use_override_color'] = opts[:'output_strokes_use_override_color'] if !opts[:'output_strokes_use_override_color'].nil?
      form_params['output.strokes.override_color'] = opts[:'output_strokes_override_color'] if !opts[:'output_strokes_override_color'].nil?
      form_params['output.gap_filler.enabled'] = opts[:'output_gap_filler_enabled'] if !opts[:'output_gap_filler_enabled'].nil?
      form_params['output.gap_filler.non_scaling_stroke'] = opts[:'output_gap_filler_non_scaling_stroke'] if !opts[:'output_gap_filler_non_scaling_stroke'].nil?
      form_params['output.gap_filler.clip'] = opts[:'output_gap_filler_clip'] if !opts[:'output_gap_filler_clip'].nil?
      form_params['output.gap_filler.stroke_width'] = opts[:'output_gap_filler_stroke_width'] if !opts[:'output_gap_filler_stroke_width'].nil?
      form_params['output.parameterized_shapes.flatten'] = opts[:'output_parameterized_shapes_flatten'] if !opts[:'output_parameterized_shapes_flatten'].nil?
      form_params['output.curves.line_fit_tolerance'] = opts[:'output_curves_line_fit_tolerance'] if !opts[:'output_curves_line_fit_tolerance'].nil?
      form_params['output.curves.allowed.quadratic_bezier'] = opts[:'output_curves_allowed_quadratic_bezier'] if !opts[:'output_curves_allowed_quadratic_bezier'].nil?
      form_params['output.curves.allowed.cubic_bezier'] = opts[:'output_curves_allowed_cubic_bezier'] if !opts[:'output_curves_allowed_cubic_bezier'].nil?
      form_params['output.curves.allowed.circular_arc'] = opts[:'output_curves_allowed_circular_arc'] if !opts[:'output_curves_allowed_circular_arc'].nil?
      form_params['output.curves.allowed.elliptical_arc'] = opts[:'output_curves_allowed_elliptical_arc'] if !opts[:'output_curves_allowed_elliptical_arc'].nil?
      form_params['output.svg.version'] = opts[:'output_svg_version'] if !opts[:'output_svg_version'].nil?
      form_params['output.svg.fixed_size'] = opts[:'output_svg_fixed_size'] if !opts[:'output_svg_fixed_size'].nil?
      form_params['output.svg.adobe_compatibility_mode'] = opts[:'output_svg_adobe_compatibility_mode'] if !opts[:'output_svg_adobe_compatibility_mode'].nil?
      form_params['output.pdf.version'] = opts[:'output_pdf_version'] if !opts[:'output_pdf_version'].nil?
      form_params['output.pdf.compression_mode'] = opts[:'output_pdf_compression_mode'] if !opts[:'output_pdf_compression_mode'].nil?
      form_params['output.eps.version'] = opts[:'output_eps_version'] if !opts[:'output_eps_version'].nil?
      form_params['output.dxf.compatibility_level'] = opts[:'output_dxf_compatibility_level'] if !opts[:'output_dxf_compatibility_level'].nil?
      form_params['output.bitmap.anti_aliasing_mode'] = opts[:'output_bitmap_anti_aliasing_mode'] if !opts[:'output_bitmap_anti_aliasing_mode'].nil?
      form_params['output.size.scale'] = opts[:'output_size_scale'] if !opts[:'output_size_scale'].nil?
      form_params['output.size.width'] = opts[:'output_size_width'] if !opts[:'output_size_width'].nil?
      form_params['output.size.height'] = opts[:'output_size_height'] if !opts[:'output_size_height'].nil?
      form_params['output.size.unit'] = opts[:'output_size_unit'] if !opts[:'output_size_unit'].nil?
      form_params['output.size.aspect_ratio'] = opts[:'output_size_aspect_ratio'] if !opts[:'output_size_aspect_ratio'].nil?
      form_params['output.size.align_x'] = opts[:'output_size_align_x'] if !opts[:'output_size_align_x'].nil?
      form_params['output.size.align_y'] = opts[:'output_size_align_y'] if !opts[:'output_size_align_y'].nil?
      form_params['output.size.input_dpi'] = opts[:'output_size_input_dpi'] if !opts[:'output_size_input_dpi'].nil?
      form_params['output.size.output_dpi'] = opts[:'output_size_output_dpi'] if !opts[:'output_size_output_dpi'].nil?

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'File'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['basicAuth']

      new_options = opts.merge(
        :operation => :"VectorizationApi.post_download",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: VectorizationApi#post_download\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Vectorize an image
    # Submit exactly one image source as multipart form data: image, image.url, image.base64, or image.token. The response body is the generated SVG, EPS, PDF, DXF, or PNG file selected by output.file_format. Clients should allow an idle timeout of at least 180 seconds.
    # @param [Hash] opts the parameters
    # @option opts [File] :image Binary file upload of the image to vectorize. Accepts .bmp, .gif, .jpeg, .png, or .tiff files.
    # @option opts [String] :image_url URL to fetch the input image from for vectorization.
    # @option opts [String] :image_base64 Base64-encoded string of the input image. Maximum size 1 megabyte.
    # @option opts [String] :image_token An Image Token returned from an earlier vectorization call with policy.retention_days &gt; 0.
    # @option opts [String] :mode Mode of operation, useful during integration work. (default to 'production')
    # @option opts [Integer] :input_max_pixels Maximum input image size (width × height in pixels) before resizing. (default to 2097252)
    # @option opts [Integer] :policy_retention_days Number of days to retain the uploaded image and its results for re-use. (default to 0)
    # @option opts [Integer] :processing_max_colors Maximum number of colors allowed in the vectorization result. 0 means unlimited. (default to 0)
    # @option opts [Float] :processing_shapes_min_area_px Minimum shape area (in pixels) to keep in the result; smaller shapes are discarded. (default to 0.125)
    # @option opts [String] :processing_palette Palette remapping and color control, using &#39;[color][-&gt; remapped][~ tolerance];&#39; format.
    # @option opts [String] :processing_color_profile_input How to handle ICC profiles embedded in input images. (default to 'ignore')
    # @option opts [String] :processing_color_profile_output ICC profile behavior for output files: preserve, ignore. (default to 'ignore')
    # @option opts [Boolean] :processing_parameterized_shapes_ellipse_general_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_ellipse_circle_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_triangle_general_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_triangle_isosceles_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_quadrilateral_general_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_quadrilateral_rectangle_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_quadrilateral_bullet_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_star_n3_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_star_n4_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_star_n5_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_star_n6_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [String] :output_file_format Output file format to generate. (default to 'svg')
    # @option opts [String] :output_shape_stacking Whether shapes are cut out of each other or stacked atop each other. (default to 'cutouts')
    # @option opts [String] :output_group_by Grouping of shapes in output. (default to 'none')
    # @option opts [String] :output_draw_style How shapes are rendered. (default to 'fill_shapes')
    # @option opts [Float] :output_strokes_stroke_width Width of stroke for shape outlines (when enabled). (default to 1)
    # @option opts [Boolean] :output_strokes_non_scaling_stroke Use non-scaling strokes when drawing shape outlines. (default to true)
    # @option opts [Boolean] :output_strokes_use_override_color Override shape color with a specific color. (default to false)
    # @option opts [String] :output_strokes_override_color Color value to override shape stroke color if enabled. Must be in &#39;#RRGGBB&#39; or &#39;rgba(r,g,b,a)&#39; format. (default to '#000000')
    # @option opts [Boolean] :output_gap_filler_enabled Enable filling small visual gaps caused by vector rendering artifacts. (default to true)
    # @option opts [Boolean] :output_gap_filler_non_scaling_stroke Use non-scaling strokes for gap filling. (default to true)
    # @option opts [Boolean] :output_gap_filler_clip Clip gap filler strokes to shape bounds when stacking shapes. (default to false)
    # @option opts [Float] :output_gap_filler_stroke_width Width of the gap filler strokes (in output units). (default to 2)
    # @option opts [Boolean] :output_parameterized_shapes_flatten Whether to flatten detected circles, rectangles, and stars to curves. (default to false)
    # @option opts [Float] :output_curves_line_fit_tolerance Maximum allowed error when approximating curves with line segments. (default to 0.1)
    # @option opts [Boolean] :output_curves_allowed_quadratic_bezier Allow quadratic Bézier curves in the output. (default to true)
    # @option opts [Boolean] :output_curves_allowed_cubic_bezier Allow cubic Bézier curves in the output. (default to true)
    # @option opts [Boolean] :output_curves_allowed_circular_arc Allow circular arcs in the output. (default to true)
    # @option opts [Boolean] :output_curves_allowed_elliptical_arc Allow elliptical arcs in the output. (default to true)
    # @option opts [String] :output_svg_version SVG version to declare in the SVG output. (default to 'svg_1_1')
    # @option opts [Boolean] :output_svg_fixed_size Whether to fix the SVG dimensions in the output file. (default to false)
    # @option opts [Boolean] :output_svg_adobe_compatibility_mode Enable Illustrator compatibility by disabling unsupported SVG features. (default to false)
    # @option opts [String] :output_pdf_version PDF version to generate for PDF output. (default to 'PDF_1_4')
    # @option opts [String] :output_pdf_compression_mode Compression method to apply to PDF output streams. (default to 'Deflate')
    # @option opts [String] :output_eps_version EPS format version for EPS output. (default to 'PS_3_0_EPSF_3_0')
    # @option opts [String] :output_dxf_compatibility_level Level of primitive support for DXF output. (default to 'lines_and_arcs')
    # @option opts [String] :output_bitmap_anti_aliasing_mode Anti-aliasing mode for bitmap (PNG) output. (default to 'anti_aliased')
    # @option opts [Float] :output_size_scale Overall uniform scaling factor for the output image.
    # @option opts [Float] :output_size_width Output width, in the selected unit (see output.size.unit).
    # @option opts [Float] :output_size_height Output height, in the selected unit (see output.size.unit).
    # @option opts [String] :output_size_unit Measurement unit for output dimensions. (default to 'none')
    # @option opts [String] :output_size_aspect_ratio How to preserve or stretch aspect ratio. (default to 'preserve_inset')
    # @option opts [Float] :output_size_align_x Horizontal alignment (0.0 &#x3D; left, 0.5 &#x3D; center, 1.0 &#x3D; right) when aspect ratio is preserved. (default to 0.5)
    # @option opts [Float] :output_size_align_y Vertical alignment (0.0 &#x3D; top, 0.5 &#x3D; center, 1.0 &#x3D; bottom) when aspect ratio is preserved. (default to 0.5)
    # @option opts [Float] :output_size_input_dpi Override the detected DPI of the input image for size computations.
    # @option opts [Float] :output_size_output_dpi DPI setting for the output image.
    # @return [File]
    def post_vectorize(opts = {})
      data, _status_code, _headers = post_vectorize_with_http_info(opts)
      data
    end

    # Vectorize an image
    # Submit exactly one image source as multipart form data: image, image.url, image.base64, or image.token. The response body is the generated SVG, EPS, PDF, DXF, or PNG file selected by output.file_format. Clients should allow an idle timeout of at least 180 seconds.
    # @param [Hash] opts the parameters
    # @option opts [File] :image Binary file upload of the image to vectorize. Accepts .bmp, .gif, .jpeg, .png, or .tiff files.
    # @option opts [String] :image_url URL to fetch the input image from for vectorization.
    # @option opts [String] :image_base64 Base64-encoded string of the input image. Maximum size 1 megabyte.
    # @option opts [String] :image_token An Image Token returned from an earlier vectorization call with policy.retention_days &gt; 0.
    # @option opts [String] :mode Mode of operation, useful during integration work. (default to 'production')
    # @option opts [Integer] :input_max_pixels Maximum input image size (width × height in pixels) before resizing. (default to 2097252)
    # @option opts [Integer] :policy_retention_days Number of days to retain the uploaded image and its results for re-use. (default to 0)
    # @option opts [Integer] :processing_max_colors Maximum number of colors allowed in the vectorization result. 0 means unlimited. (default to 0)
    # @option opts [Float] :processing_shapes_min_area_px Minimum shape area (in pixels) to keep in the result; smaller shapes are discarded. (default to 0.125)
    # @option opts [String] :processing_palette Palette remapping and color control, using &#39;[color][-&gt; remapped][~ tolerance];&#39; format.
    # @option opts [String] :processing_color_profile_input How to handle ICC profiles embedded in input images. (default to 'ignore')
    # @option opts [String] :processing_color_profile_output ICC profile behavior for output files: preserve, ignore. (default to 'ignore')
    # @option opts [Boolean] :processing_parameterized_shapes_ellipse_general_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_ellipse_circle_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_triangle_general_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_triangle_isosceles_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_quadrilateral_general_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_quadrilateral_rectangle_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_quadrilateral_bullet_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_star_n3_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_star_n4_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_star_n5_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [Boolean] :processing_parameterized_shapes_star_n6_enabled Enable detection and parameterization of this parameterized shape type. (default to true)
    # @option opts [String] :output_file_format Output file format to generate. (default to 'svg')
    # @option opts [String] :output_shape_stacking Whether shapes are cut out of each other or stacked atop each other. (default to 'cutouts')
    # @option opts [String] :output_group_by Grouping of shapes in output. (default to 'none')
    # @option opts [String] :output_draw_style How shapes are rendered. (default to 'fill_shapes')
    # @option opts [Float] :output_strokes_stroke_width Width of stroke for shape outlines (when enabled). (default to 1)
    # @option opts [Boolean] :output_strokes_non_scaling_stroke Use non-scaling strokes when drawing shape outlines. (default to true)
    # @option opts [Boolean] :output_strokes_use_override_color Override shape color with a specific color. (default to false)
    # @option opts [String] :output_strokes_override_color Color value to override shape stroke color if enabled. Must be in &#39;#RRGGBB&#39; or &#39;rgba(r,g,b,a)&#39; format. (default to '#000000')
    # @option opts [Boolean] :output_gap_filler_enabled Enable filling small visual gaps caused by vector rendering artifacts. (default to true)
    # @option opts [Boolean] :output_gap_filler_non_scaling_stroke Use non-scaling strokes for gap filling. (default to true)
    # @option opts [Boolean] :output_gap_filler_clip Clip gap filler strokes to shape bounds when stacking shapes. (default to false)
    # @option opts [Float] :output_gap_filler_stroke_width Width of the gap filler strokes (in output units). (default to 2)
    # @option opts [Boolean] :output_parameterized_shapes_flatten Whether to flatten detected circles, rectangles, and stars to curves. (default to false)
    # @option opts [Float] :output_curves_line_fit_tolerance Maximum allowed error when approximating curves with line segments. (default to 0.1)
    # @option opts [Boolean] :output_curves_allowed_quadratic_bezier Allow quadratic Bézier curves in the output. (default to true)
    # @option opts [Boolean] :output_curves_allowed_cubic_bezier Allow cubic Bézier curves in the output. (default to true)
    # @option opts [Boolean] :output_curves_allowed_circular_arc Allow circular arcs in the output. (default to true)
    # @option opts [Boolean] :output_curves_allowed_elliptical_arc Allow elliptical arcs in the output. (default to true)
    # @option opts [String] :output_svg_version SVG version to declare in the SVG output. (default to 'svg_1_1')
    # @option opts [Boolean] :output_svg_fixed_size Whether to fix the SVG dimensions in the output file. (default to false)
    # @option opts [Boolean] :output_svg_adobe_compatibility_mode Enable Illustrator compatibility by disabling unsupported SVG features. (default to false)
    # @option opts [String] :output_pdf_version PDF version to generate for PDF output. (default to 'PDF_1_4')
    # @option opts [String] :output_pdf_compression_mode Compression method to apply to PDF output streams. (default to 'Deflate')
    # @option opts [String] :output_eps_version EPS format version for EPS output. (default to 'PS_3_0_EPSF_3_0')
    # @option opts [String] :output_dxf_compatibility_level Level of primitive support for DXF output. (default to 'lines_and_arcs')
    # @option opts [String] :output_bitmap_anti_aliasing_mode Anti-aliasing mode for bitmap (PNG) output. (default to 'anti_aliased')
    # @option opts [Float] :output_size_scale Overall uniform scaling factor for the output image.
    # @option opts [Float] :output_size_width Output width, in the selected unit (see output.size.unit).
    # @option opts [Float] :output_size_height Output height, in the selected unit (see output.size.unit).
    # @option opts [String] :output_size_unit Measurement unit for output dimensions. (default to 'none')
    # @option opts [String] :output_size_aspect_ratio How to preserve or stretch aspect ratio. (default to 'preserve_inset')
    # @option opts [Float] :output_size_align_x Horizontal alignment (0.0 &#x3D; left, 0.5 &#x3D; center, 1.0 &#x3D; right) when aspect ratio is preserved. (default to 0.5)
    # @option opts [Float] :output_size_align_y Vertical alignment (0.0 &#x3D; top, 0.5 &#x3D; center, 1.0 &#x3D; bottom) when aspect ratio is preserved. (default to 0.5)
    # @option opts [Float] :output_size_input_dpi Override the detected DPI of the input image for size computations.
    # @option opts [Float] :output_size_output_dpi DPI setting for the output image.
    # @return [Array<(File, Integer, Hash)>] File data, response status code and response headers
    def post_vectorize_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: VectorizationApi.post_vectorize ...'
      end
      # unbox the parameters from the hash
      allowable_values = ["production", "preview", "test", "test_preview"]
      if @api_client.config.client_side_validation && opts[:'mode'] && !allowable_values.include?(opts[:'mode'])
        fail ArgumentError, "invalid value for \"mode\", must be one of #{allowable_values}"
      end
      if @api_client.config.client_side_validation && !opts[:'input_max_pixels'].nil? && opts[:'input_max_pixels'] > 3145828
        fail ArgumentError, 'invalid value for "opts[:"input_max_pixels"]" when calling VectorizationApi.post_vectorize, must be smaller than or equal to 3145828.'
      end

      if @api_client.config.client_side_validation && !opts[:'input_max_pixels'].nil? && opts[:'input_max_pixels'] < 100
        fail ArgumentError, 'invalid value for "opts[:"input_max_pixels"]" when calling VectorizationApi.post_vectorize, must be greater than or equal to 100.'
      end

      if @api_client.config.client_side_validation && !opts[:'policy_retention_days'].nil? && opts[:'policy_retention_days'] > 30
        fail ArgumentError, 'invalid value for "opts[:"policy_retention_days"]" when calling VectorizationApi.post_vectorize, must be smaller than or equal to 30.'
      end

      if @api_client.config.client_side_validation && !opts[:'policy_retention_days'].nil? && opts[:'policy_retention_days'] < 0
        fail ArgumentError, 'invalid value for "opts[:"policy_retention_days"]" when calling VectorizationApi.post_vectorize, must be greater than or equal to 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'processing_max_colors'].nil? && opts[:'processing_max_colors'] > 256
        fail ArgumentError, 'invalid value for "opts[:"processing_max_colors"]" when calling VectorizationApi.post_vectorize, must be smaller than or equal to 256.'
      end

      if @api_client.config.client_side_validation && !opts[:'processing_max_colors'].nil? && opts[:'processing_max_colors'] < 0
        fail ArgumentError, 'invalid value for "opts[:"processing_max_colors"]" when calling VectorizationApi.post_vectorize, must be greater than or equal to 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'processing_shapes_min_area_px'].nil? && opts[:'processing_shapes_min_area_px'] > 100
        fail ArgumentError, 'invalid value for "opts[:"processing_shapes_min_area_px"]" when calling VectorizationApi.post_vectorize, must be smaller than or equal to 100.'
      end

      if @api_client.config.client_side_validation && !opts[:'processing_shapes_min_area_px'].nil? && opts[:'processing_shapes_min_area_px'] < 0
        fail ArgumentError, 'invalid value for "opts[:"processing_shapes_min_area_px"]" when calling VectorizationApi.post_vectorize, must be greater than or equal to 0.'
      end

      allowable_values = ["ignore", "preserve"]
      if @api_client.config.client_side_validation && opts[:'processing_color_profile_input'] && !allowable_values.include?(opts[:'processing_color_profile_input'])
        fail ArgumentError, "invalid value for \"processing_color_profile_input\", must be one of #{allowable_values}"
      end
      allowable_values = ["svg", "eps", "pdf", "dxf", "png"]
      if @api_client.config.client_side_validation && opts[:'output_file_format'] && !allowable_values.include?(opts[:'output_file_format'])
        fail ArgumentError, "invalid value for \"output_file_format\", must be one of #{allowable_values}"
      end
      allowable_values = ["cutouts", "stacked"]
      if @api_client.config.client_side_validation && opts[:'output_shape_stacking'] && !allowable_values.include?(opts[:'output_shape_stacking'])
        fail ArgumentError, "invalid value for \"output_shape_stacking\", must be one of #{allowable_values}"
      end
      allowable_values = ["none", "color", "parent", "layer"]
      if @api_client.config.client_side_validation && opts[:'output_group_by'] && !allowable_values.include?(opts[:'output_group_by'])
        fail ArgumentError, "invalid value for \"output_group_by\", must be one of #{allowable_values}"
      end
      allowable_values = ["fill_shapes", "stroke_shapes", "stroke_edges"]
      if @api_client.config.client_side_validation && opts[:'output_draw_style'] && !allowable_values.include?(opts[:'output_draw_style'])
        fail ArgumentError, "invalid value for \"output_draw_style\", must be one of #{allowable_values}"
      end
      if @api_client.config.client_side_validation && !opts[:'output_strokes_stroke_width'].nil? && opts[:'output_strokes_stroke_width'] > 5
        fail ArgumentError, 'invalid value for "opts[:"output_strokes_stroke_width"]" when calling VectorizationApi.post_vectorize, must be smaller than or equal to 5.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_strokes_stroke_width'].nil? && opts[:'output_strokes_stroke_width'] < 0
        fail ArgumentError, 'invalid value for "opts[:"output_strokes_stroke_width"]" when calling VectorizationApi.post_vectorize, must be greater than or equal to 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_gap_filler_stroke_width'].nil? && opts[:'output_gap_filler_stroke_width'] > 5
        fail ArgumentError, 'invalid value for "opts[:"output_gap_filler_stroke_width"]" when calling VectorizationApi.post_vectorize, must be smaller than or equal to 5.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_gap_filler_stroke_width'].nil? && opts[:'output_gap_filler_stroke_width'] < 0
        fail ArgumentError, 'invalid value for "opts[:"output_gap_filler_stroke_width"]" when calling VectorizationApi.post_vectorize, must be greater than or equal to 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_curves_line_fit_tolerance'].nil? && opts[:'output_curves_line_fit_tolerance'] > 1
        fail ArgumentError, 'invalid value for "opts[:"output_curves_line_fit_tolerance"]" when calling VectorizationApi.post_vectorize, must be smaller than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_curves_line_fit_tolerance'].nil? && opts[:'output_curves_line_fit_tolerance'] < 0.001
        fail ArgumentError, 'invalid value for "opts[:"output_curves_line_fit_tolerance"]" when calling VectorizationApi.post_vectorize, must be greater than or equal to 0.001.'
      end

      allowable_values = ["svg_1_0", "svg_1_1", "svg_tiny_1_2"]
      if @api_client.config.client_side_validation && opts[:'output_svg_version'] && !allowable_values.include?(opts[:'output_svg_version'])
        fail ArgumentError, "invalid value for \"output_svg_version\", must be one of #{allowable_values}"
      end
      allowable_values = ["PDF_1_4"]
      if @api_client.config.client_side_validation && opts[:'output_pdf_version'] && !allowable_values.include?(opts[:'output_pdf_version'])
        fail ArgumentError, "invalid value for \"output_pdf_version\", must be one of #{allowable_values}"
      end
      allowable_values = ["None", "Deflate"]
      if @api_client.config.client_side_validation && opts[:'output_pdf_compression_mode'] && !allowable_values.include?(opts[:'output_pdf_compression_mode'])
        fail ArgumentError, "invalid value for \"output_pdf_compression_mode\", must be one of #{allowable_values}"
      end
      allowable_values = ["PS_3_0_EPSF_3_0"]
      if @api_client.config.client_side_validation && opts[:'output_eps_version'] && !allowable_values.include?(opts[:'output_eps_version'])
        fail ArgumentError, "invalid value for \"output_eps_version\", must be one of #{allowable_values}"
      end
      allowable_values = ["lines_only", "lines_and_arcs", "lines_arcs_and_splines"]
      if @api_client.config.client_side_validation && opts[:'output_dxf_compatibility_level'] && !allowable_values.include?(opts[:'output_dxf_compatibility_level'])
        fail ArgumentError, "invalid value for \"output_dxf_compatibility_level\", must be one of #{allowable_values}"
      end
      allowable_values = ["anti_aliased", "aliased"]
      if @api_client.config.client_side_validation && opts[:'output_bitmap_anti_aliasing_mode'] && !allowable_values.include?(opts[:'output_bitmap_anti_aliasing_mode'])
        fail ArgumentError, "invalid value for \"output_bitmap_anti_aliasing_mode\", must be one of #{allowable_values}"
      end
      if @api_client.config.client_side_validation && !opts[:'output_size_scale'].nil? && opts[:'output_size_scale'] > 1000
        fail ArgumentError, 'invalid value for "opts[:"output_size_scale"]" when calling VectorizationApi.post_vectorize, must be smaller than or equal to 1000.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_scale'].nil? && opts[:'output_size_scale'] < 0
        fail ArgumentError, 'invalid value for "opts[:"output_size_scale"]" when calling VectorizationApi.post_vectorize, must be greater than or equal to 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_width'].nil? && opts[:'output_size_width'] > 1000000000000
        fail ArgumentError, 'invalid value for "opts[:"output_size_width"]" when calling VectorizationApi.post_vectorize, must be smaller than or equal to 1000000000000.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_width'].nil? && opts[:'output_size_width'] < 0
        fail ArgumentError, 'invalid value for "opts[:"output_size_width"]" when calling VectorizationApi.post_vectorize, must be greater than or equal to 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_height'].nil? && opts[:'output_size_height'] > 1000000000000
        fail ArgumentError, 'invalid value for "opts[:"output_size_height"]" when calling VectorizationApi.post_vectorize, must be smaller than or equal to 1000000000000.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_height'].nil? && opts[:'output_size_height'] < 0
        fail ArgumentError, 'invalid value for "opts[:"output_size_height"]" when calling VectorizationApi.post_vectorize, must be greater than or equal to 0.'
      end

      allowable_values = ["none", "px", "pt", "in", "cm", "mm"]
      if @api_client.config.client_side_validation && opts[:'output_size_unit'] && !allowable_values.include?(opts[:'output_size_unit'])
        fail ArgumentError, "invalid value for \"output_size_unit\", must be one of #{allowable_values}"
      end
      allowable_values = ["preserve_inset", "preserve_overflow", "stretch"]
      if @api_client.config.client_side_validation && opts[:'output_size_aspect_ratio'] && !allowable_values.include?(opts[:'output_size_aspect_ratio'])
        fail ArgumentError, "invalid value for \"output_size_aspect_ratio\", must be one of #{allowable_values}"
      end
      if @api_client.config.client_side_validation && !opts[:'output_size_align_x'].nil? && opts[:'output_size_align_x'] > 1
        fail ArgumentError, 'invalid value for "opts[:"output_size_align_x"]" when calling VectorizationApi.post_vectorize, must be smaller than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_align_x'].nil? && opts[:'output_size_align_x'] < 0
        fail ArgumentError, 'invalid value for "opts[:"output_size_align_x"]" when calling VectorizationApi.post_vectorize, must be greater than or equal to 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_align_y'].nil? && opts[:'output_size_align_y'] > 1
        fail ArgumentError, 'invalid value for "opts[:"output_size_align_y"]" when calling VectorizationApi.post_vectorize, must be smaller than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_align_y'].nil? && opts[:'output_size_align_y'] < 0
        fail ArgumentError, 'invalid value for "opts[:"output_size_align_y"]" when calling VectorizationApi.post_vectorize, must be greater than or equal to 0.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_input_dpi'].nil? && opts[:'output_size_input_dpi'] > 1000000
        fail ArgumentError, 'invalid value for "opts[:"output_size_input_dpi"]" when calling VectorizationApi.post_vectorize, must be smaller than or equal to 1000000.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_input_dpi'].nil? && opts[:'output_size_input_dpi'] < 1
        fail ArgumentError, 'invalid value for "opts[:"output_size_input_dpi"]" when calling VectorizationApi.post_vectorize, must be greater than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_output_dpi'].nil? && opts[:'output_size_output_dpi'] > 1000000
        fail ArgumentError, 'invalid value for "opts[:"output_size_output_dpi"]" when calling VectorizationApi.post_vectorize, must be smaller than or equal to 1000000.'
      end

      if @api_client.config.client_side_validation && !opts[:'output_size_output_dpi'].nil? && opts[:'output_size_output_dpi'] < 1
        fail ArgumentError, 'invalid value for "opts[:"output_size_output_dpi"]" when calling VectorizationApi.post_vectorize, must be greater than or equal to 1.'
      end

      # resource path
      local_var_path = '/vectorize'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['image/svg+xml', 'application/postscript', 'application/pdf', 'application/dxf', 'image/png', 'application/json'])
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}
      form_params['image'] = opts[:'image'] if !opts[:'image'].nil?
      form_params['image.url'] = opts[:'image_url'] if !opts[:'image_url'].nil?
      form_params['image.base64'] = opts[:'image_base64'] if !opts[:'image_base64'].nil?
      form_params['image.token'] = opts[:'image_token'] if !opts[:'image_token'].nil?
      form_params['mode'] = opts[:'mode'] if !opts[:'mode'].nil?
      form_params['input.max_pixels'] = opts[:'input_max_pixels'] if !opts[:'input_max_pixels'].nil?
      form_params['policy.retention_days'] = opts[:'policy_retention_days'] if !opts[:'policy_retention_days'].nil?
      form_params['processing.max_colors'] = opts[:'processing_max_colors'] if !opts[:'processing_max_colors'].nil?
      form_params['processing.shapes.min_area_px'] = opts[:'processing_shapes_min_area_px'] if !opts[:'processing_shapes_min_area_px'].nil?
      form_params['processing.palette'] = opts[:'processing_palette'] if !opts[:'processing_palette'].nil?
      form_params['processing.color_profile.input'] = opts[:'processing_color_profile_input'] if !opts[:'processing_color_profile_input'].nil?
      form_params['processing.color_profile.output'] = opts[:'processing_color_profile_output'] if !opts[:'processing_color_profile_output'].nil?
      form_params['processing.parameterizedShapes.ellipse.general.enabled'] = opts[:'processing_parameterized_shapes_ellipse_general_enabled'] if !opts[:'processing_parameterized_shapes_ellipse_general_enabled'].nil?
      form_params['processing.parameterizedShapes.ellipse.circle.enabled'] = opts[:'processing_parameterized_shapes_ellipse_circle_enabled'] if !opts[:'processing_parameterized_shapes_ellipse_circle_enabled'].nil?
      form_params['processing.parameterizedShapes.triangle.general.enabled'] = opts[:'processing_parameterized_shapes_triangle_general_enabled'] if !opts[:'processing_parameterized_shapes_triangle_general_enabled'].nil?
      form_params['processing.parameterizedShapes.triangle.isosceles.enabled'] = opts[:'processing_parameterized_shapes_triangle_isosceles_enabled'] if !opts[:'processing_parameterized_shapes_triangle_isosceles_enabled'].nil?
      form_params['processing.parameterizedShapes.quadrilateral.general.enabled'] = opts[:'processing_parameterized_shapes_quadrilateral_general_enabled'] if !opts[:'processing_parameterized_shapes_quadrilateral_general_enabled'].nil?
      form_params['processing.parameterizedShapes.quadrilateral.rectangle.enabled'] = opts[:'processing_parameterized_shapes_quadrilateral_rectangle_enabled'] if !opts[:'processing_parameterized_shapes_quadrilateral_rectangle_enabled'].nil?
      form_params['processing.parameterizedShapes.quadrilateral.bullet.enabled'] = opts[:'processing_parameterized_shapes_quadrilateral_bullet_enabled'] if !opts[:'processing_parameterized_shapes_quadrilateral_bullet_enabled'].nil?
      form_params['processing.parameterizedShapes.star.N3.enabled'] = opts[:'processing_parameterized_shapes_star_n3_enabled'] if !opts[:'processing_parameterized_shapes_star_n3_enabled'].nil?
      form_params['processing.parameterizedShapes.star.N4.enabled'] = opts[:'processing_parameterized_shapes_star_n4_enabled'] if !opts[:'processing_parameterized_shapes_star_n4_enabled'].nil?
      form_params['processing.parameterizedShapes.star.N5.enabled'] = opts[:'processing_parameterized_shapes_star_n5_enabled'] if !opts[:'processing_parameterized_shapes_star_n5_enabled'].nil?
      form_params['processing.parameterizedShapes.star.N6.enabled'] = opts[:'processing_parameterized_shapes_star_n6_enabled'] if !opts[:'processing_parameterized_shapes_star_n6_enabled'].nil?
      form_params['output.file_format'] = opts[:'output_file_format'] if !opts[:'output_file_format'].nil?
      form_params['output.shape_stacking'] = opts[:'output_shape_stacking'] if !opts[:'output_shape_stacking'].nil?
      form_params['output.group_by'] = opts[:'output_group_by'] if !opts[:'output_group_by'].nil?
      form_params['output.draw_style'] = opts[:'output_draw_style'] if !opts[:'output_draw_style'].nil?
      form_params['output.strokes.stroke_width'] = opts[:'output_strokes_stroke_width'] if !opts[:'output_strokes_stroke_width'].nil?
      form_params['output.strokes.non_scaling_stroke'] = opts[:'output_strokes_non_scaling_stroke'] if !opts[:'output_strokes_non_scaling_stroke'].nil?
      form_params['output.strokes.use_override_color'] = opts[:'output_strokes_use_override_color'] if !opts[:'output_strokes_use_override_color'].nil?
      form_params['output.strokes.override_color'] = opts[:'output_strokes_override_color'] if !opts[:'output_strokes_override_color'].nil?
      form_params['output.gap_filler.enabled'] = opts[:'output_gap_filler_enabled'] if !opts[:'output_gap_filler_enabled'].nil?
      form_params['output.gap_filler.non_scaling_stroke'] = opts[:'output_gap_filler_non_scaling_stroke'] if !opts[:'output_gap_filler_non_scaling_stroke'].nil?
      form_params['output.gap_filler.clip'] = opts[:'output_gap_filler_clip'] if !opts[:'output_gap_filler_clip'].nil?
      form_params['output.gap_filler.stroke_width'] = opts[:'output_gap_filler_stroke_width'] if !opts[:'output_gap_filler_stroke_width'].nil?
      form_params['output.parameterized_shapes.flatten'] = opts[:'output_parameterized_shapes_flatten'] if !opts[:'output_parameterized_shapes_flatten'].nil?
      form_params['output.curves.line_fit_tolerance'] = opts[:'output_curves_line_fit_tolerance'] if !opts[:'output_curves_line_fit_tolerance'].nil?
      form_params['output.curves.allowed.quadratic_bezier'] = opts[:'output_curves_allowed_quadratic_bezier'] if !opts[:'output_curves_allowed_quadratic_bezier'].nil?
      form_params['output.curves.allowed.cubic_bezier'] = opts[:'output_curves_allowed_cubic_bezier'] if !opts[:'output_curves_allowed_cubic_bezier'].nil?
      form_params['output.curves.allowed.circular_arc'] = opts[:'output_curves_allowed_circular_arc'] if !opts[:'output_curves_allowed_circular_arc'].nil?
      form_params['output.curves.allowed.elliptical_arc'] = opts[:'output_curves_allowed_elliptical_arc'] if !opts[:'output_curves_allowed_elliptical_arc'].nil?
      form_params['output.svg.version'] = opts[:'output_svg_version'] if !opts[:'output_svg_version'].nil?
      form_params['output.svg.fixed_size'] = opts[:'output_svg_fixed_size'] if !opts[:'output_svg_fixed_size'].nil?
      form_params['output.svg.adobe_compatibility_mode'] = opts[:'output_svg_adobe_compatibility_mode'] if !opts[:'output_svg_adobe_compatibility_mode'].nil?
      form_params['output.pdf.version'] = opts[:'output_pdf_version'] if !opts[:'output_pdf_version'].nil?
      form_params['output.pdf.compression_mode'] = opts[:'output_pdf_compression_mode'] if !opts[:'output_pdf_compression_mode'].nil?
      form_params['output.eps.version'] = opts[:'output_eps_version'] if !opts[:'output_eps_version'].nil?
      form_params['output.dxf.compatibility_level'] = opts[:'output_dxf_compatibility_level'] if !opts[:'output_dxf_compatibility_level'].nil?
      form_params['output.bitmap.anti_aliasing_mode'] = opts[:'output_bitmap_anti_aliasing_mode'] if !opts[:'output_bitmap_anti_aliasing_mode'].nil?
      form_params['output.size.scale'] = opts[:'output_size_scale'] if !opts[:'output_size_scale'].nil?
      form_params['output.size.width'] = opts[:'output_size_width'] if !opts[:'output_size_width'].nil?
      form_params['output.size.height'] = opts[:'output_size_height'] if !opts[:'output_size_height'].nil?
      form_params['output.size.unit'] = opts[:'output_size_unit'] if !opts[:'output_size_unit'].nil?
      form_params['output.size.aspect_ratio'] = opts[:'output_size_aspect_ratio'] if !opts[:'output_size_aspect_ratio'].nil?
      form_params['output.size.align_x'] = opts[:'output_size_align_x'] if !opts[:'output_size_align_x'].nil?
      form_params['output.size.align_y'] = opts[:'output_size_align_y'] if !opts[:'output_size_align_y'].nil?
      form_params['output.size.input_dpi'] = opts[:'output_size_input_dpi'] if !opts[:'output_size_input_dpi'].nil?
      form_params['output.size.output_dpi'] = opts[:'output_size_output_dpi'] if !opts[:'output_size_output_dpi'].nil?

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'File'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['basicAuth']

      new_options = opts.merge(
        :operation => :"VectorizationApi.post_vectorize",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: VectorizationApi#post_vectorize\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
